version: '3'
services: 

  api:
    build: ./api
    environment: 
      - ACCESS_CONTROL_ORIGIN=*
    restart: always
    expose:
      - 3000

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - api

  web:
    build: ./web
    restart: always
    ports:
      - 4444:4444
    depends_on: 
      - nginx